### ISSUE TITLE
NoMethodError undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by gustiando** [sous-chefs/java#178]
Is this a bug? I had the same issue.
http://stackoverflow.com/questions/17785340/got-undefined-method-for-nilnilclass-installing-java-cookbook/23510333#23510333

**Comment by phs** [comment]
[For posterity](https://xkcd.com/979/), when I smacked into this just now it was simply because I forgot to add `depends 'java'` to `metadata.rb`.
