### ISSUE TITLE
Refactor this cookbook in terms of LWRPs

### ISSUE THREAD

**Issue by mifisignal** [sous-chefs/java#197]
As a user, I should be able to install any permutation of JDKs/JREs on a node, whether they be official Sun/Oracle builds, IBM builds or OpenJDK builds, into any directory that can be specified as a JAVA_HOME.

As currently designed, this cookbook cannot provide this functionality, because it uses recipes instead of LWRPs.  The user is therefore currently limited to  installing one of each "flavor" provided by a given recipe.  (The exception is any Java provided by the java_ark provider, but this should be the rule, not the exception.)

**Comment by jkleinlercher** [comment]
is it also possible to install the IBM JDK with the java_ark lwrp ?
