### ISSUE TITLE
cookbook doesnt work for jdk 7_u51

### ISSUE THREAD

**Issue by medyagh** [sous-chefs/java#209]
```
* remote_file[/var/chef/cache/jdk-7u51-linux-x64.gz] action create_if_missing (up to date)
```

[2014-09-26T18:09:41-04:00] FATAL:  Command ' mv "/var/chef/cache/jdk1.7.0_51" "/tools/utilsw/jdk1.7.0_51" ' failed

**Comment by miguelaferreira** [comment]
I got here following from #208 and would like to let you know how I fixed my problem.

I had the same error reported in #208, and I figured that the problem was that the docker container where I'm running my kitchen tests did not have the `tar` utility, and therefore the error.
