### ISSUE TITLE
openjdk hardcoded ppa reference

### ISSUE THREAD

**Issue by ChefUser2016** [sous-chefs/java#387]
I'm using version java cookook 1,42.  I need a way to override the default configured ppa for openjdk, which goes directly to launchpad.net.

We host our own internal Ubuntu repos, and are hosting the openjdk there, so that VMs don't have to get openjdk externally - http://repo-mirror.xxxx/ppa/openjdk-r/ppa/ubuntu/pool/main/o/openjdk-7/?C=M;O=D.

Running apt-get update includes openjdk, with /etc/apt/sources list pointing to the above repo.

Since version 1.36 the java cookbook is pulling openjdk directly from launchpad, and there is no easy way to prevent that. The result is the java cookbook fails to run if the VM has no external access.

I would like the java cookbook to expose the ppa location as an attribute so it can be overridden with a local ppa location,

**Comment by quulah** [comment]
Enabling or disabling the PPA could also be an attribute. I have no need for it, the repositories are handled elsewhere with no access to Launchpad.

Or if you want to handle it with just one attribute, like the location, give us an opportunity to set it to nil and not break.

**Comment by erichelgeson** [comment]
Thanks for the bug report - this is an easy first contribution for someone to pickup.

**Comment by damacus** [comment]
Closed as a fix has now been merged.

Thanks,
Sous-Chefs
