### ISSUE TITLE
chef 13 error in java_certificate

### ISSUE THREAD

**Issue by supergicko** [sous-chefs/java#414]
Hi guys,

chef 13 is on the way, and Test Kitchen is spitting out some deprecation warnings when using the (very cool) `java_certificate` resource.

Output:
```
[2017-04-10T11:55:54+00:00] WARN: Class Chef::Provider::JavaCertificate does not declare 'provides :java_certificate'.
[2017-04-10T11:55:54+00:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
```

**Comment by pantocrator27** [comment]
With Chef 13 now being released, this is now broken.

**Comment by tas50** [comment]
Fixed by https://github.com/agileorbit-cookbooks/java/pull/412

**Comment by taiphun** [comment]
Has this actually made it into a build yet?

**Comment by askmike1** [comment]
Has any progress been made on getting the above into a release considering Chef12 is EOL in one month?

**Comment by tas50** [comment]
It's probably worth merging the above into master and getting some eyes on it. I'm super deep in Chef 14 work right now and I don't have the time to carve out to continue to hack on that branch. That being said it's super important that we get that merged in for everyone relying on this cookbook.

**Comment by taiphun** [comment]
Been waiting on this one for a LONG time.  
I'm using this cookbook with a serious hack to get my certificates working for Chef 13.  
Any idea when this one will make it in?  We haven't seen a release in 10 months.

**Comment by majormoses** [comment]
Apologies on the long delay there have been a number of releases that have included this. I am gonna close this out if you pull the latest and have issues please reply so we can open it back up.
