### ISSUE TITLE
metadata.rb says it supports chef >12.1 but chef_version came in 12.6

### ISSUE THREAD

**Issue by el-gee** [sous-chefs/java#436]
https://github.com/agileorbit-cookbooks/java/blob/master/metadata.rb#L53 however if you look through https://docs.chef.io/release_notes.html and search for `chef_version` you'll notice it wasn't introduced till 12.6.  

This indeed does fail for me while running chef-client version 12.5.

The apt cookbook does the metadata a little differentlyhttps://github.com/chef-cookbooks/apt/blob/master/metadata.rb#L19 and I believe this would fix the issue.  Happy to PR myself if desired :smiley:

**Comment by erichelgeson** [comment]
Thanks for the report, a PR would be great :)

**Comment by tas50** [comment]
Closing this out since we require Chef 13.4 now
