### ISSUE TITLE
Different tag format for v1.50

### ISSUE THREAD

**Issue by AntonOfTheWoods** [sous-chefs/java#450]
HI,

Was it intentional to change the tag format from "vX.Y.Z" to "vX.Y"? Is it possible to add the ".Z"? 

Thanks!
Anton

**Comment by majormoses** [comment]
That does look like a mistake to me, as we have released a `2.x.z` version. I can go back and retroactively fix that but unless someone feels like its worth it I am gonna close this out. If you would like me to do this please respond and I will re-open the issue.
