### ISSUE TITLE
How to install Java 9 using openjdk?

### ISSUE THREAD

**Issue by dmigous** [sous-chefs/java#453]
I'm trying to do

```
# Install OpenJDK Java
node.default['java']['jdk_version'] = '9'
node.default['java']['install_flavor'] = 'openjdk'
node.default['java']['tarball'] = 'openjdk-9.0.1_linux-x64_bin.tar.gz'
node.default['java']['tarball_checksum'] = 'a312ea3c51940361af738fda809e08e16972ae9dd314cb087e0d31e251b416a3'
include_recipe 'java'
```
I tried without tarball\tarball_checksum params too, didn't work, still installed 8th version

but it still installs 

```
Recipe: java::openjdk
  * apt_package[openjdk-8-jdk] action install[2017-12-21T21:17:42+00:00] INFO: Processing apt_package[openjdk-8-jdk] action install (java::openjdk line 53)
 (up to date)
  * apt_package[openjdk-8-jre-headless] action install[2017-12-21T21:17:45+00:00] INFO: Processing apt_package[openjdk-8-jre-headless] action install (java::openjdk line 53)
```

but if I try to run `apt-get install openjdk-9-jdk` it installs. So package `openjdk-9-jdk` is available

**Comment by rennhak** [comment]
+1

**Comment by isuftin** [comment]
https://github.com/sous-chefs/java/blob/v2.0.1/recipes/oracle.rb#L34-L47

This cookbook does not yet seem to support Oracle JDK 9+

That's a shame considering we need to start test-driving JDK 9 and 10 on our machines.

**Comment by damacus** [comment]
Looks like this is ready to close as the mentioned PR has been merged. 

If this is incorrect please don't hesitate to reopen

Thanks!

**Comment by phomein** [comment]
Not sure if i'm missing something here but OP was asking about openjdk and the comments and PR refer to oracle.
