### ISSUE TITLE
Windows JCE installation should work with JDK or JRE

### ISSUE THREAD

**Issue by mosspilot** [sous-chefs/java#454]
When attempting to install JCE and JRE for a windows machine, I get this error:

```
==> win10-pro-x64:   * remote_file[C:\Program Files\Java\jre1.8.0_51/jre/lib/security/local_policy.jar] action create

==> win10-pro-x64:     * Parent directory C:\Program Files\Java\jre1.8.0_51/jre/lib/security does not exist.
```

I believe it is due to these lines below in the oracle_jce recipe due to the fact that the file.join includes the 'jre' folder, which is standard for a JDK but not for a JRE:

https://github.com/agileorbit-cookbooks/java/blob/afc1302fc34413752f0e46f576feedea23e54b17/recipes/oracle_jce.rb#L47-L49

**Comment by mosspilot** [comment]
On second thought, are plain old JRE's are supported?

**Comment by frezbo** [comment]
@mosspilot #458 should fix it, I have tested with JRE on windows and linux

**Comment by mosspilot** [comment]
👍  Awesome
