### ISSUE TITLE
Is this cookbook current maintained?

### ISSUE THREAD

**Issue by pantocrator27** [sous-chefs/java#457]
Is this cookbook current maintained?

**Comment by supergicko** [comment]
@erichelgeson pls give us a short statement. would be super cool to know

**Comment by rhass** [comment]
@thommay Is this something the Chef Community team can look at?

**Comment by smastrorocco** [comment]
Any word on this being maintained?

**Comment by staticfrost** [comment]
judging from the latest commits it is.

**Comment by isuftin** [comment]
But there have been PRs open since 2017 with no movement on them. 

I want to help with the code for this cookbook by making PRs but I really don't want to waste my time if they're not going to be considered and merged.

**Comment by grv87** [comment]
@tas50, could you comment on this question?

**Comment by damacus** [comment]
Hi there!

we're always looking for people to help out maintain the community cookbooks, it's really the reason sous-chefs exists.

The current community have been busy lately, and so some projects may look _dead_. However please note, sometimes projects look dead, even if they're stable(!).

We have a number of generalists in sous-chefs that would love to show some new people around, how  to create the best cookbooks we can, however those generalists often are spread thin and do not know the product which is being automated too well.

With that in mind even if it's just a README update, or typo fix, we would always encourage newcomers to get involved!
