### ISSUE TITLE
jdk10 won't install -- two issues

### ISSUE THREAD

**Issue by acqant** [sous-chefs/java#460]
Some debug below.
The major_num need to be file_name.scan(/\d+/)[0]
The update_num needs to not be 0 if it doesn't exist

       file_name jdk-10.0.1_linux-x64_bin.tar.gz
       major_num 1
       update_token 
       update_num 0
       package_name jdk

**Comment by isuftin** [comment]
It does seem as though Oracle has gone with a new versioning scheme. Seems their latest releases have gone to semantic versioning?

Ex: http://download.oracle.com/otn-pub/java/jdk/10.0.1+10/fb4372174a714e6b8c52526dc134031e/jdk-10.0.1_linux-x64_bin.tar.gz
