### ISSUE TITLE
Java 8 x86_64 URI needs updating

### ISSUE THREAD

**Issue by jsibo** [sous-chefs/java#475]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
2.1.0

### Chef-client version
[Version of chef-client in your environment]
12.21.31

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
CentOS 7 + Openstack

### Scenario:
[What you are trying to achieve and you can't?]
Java 8 x86_64 tar file hits a 404 as java 8-172 download from Oracle no longer good. Specifically, this URL mentioned in the attributes: http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz

`openstack_compute_floatingip_associate_v2.confluence-app (chef):     * yum_package[tar] action install[2018-07-18T11:49:33-05:00] INFO: Processing yum_package[tar] action install (/var/chef/cache/cookbooks/java/resources/oracle_install.rb line 105)
openstack_compute_floatingip_associate_v2.confluence-app (chef):  (up to date)
openstack_compute_floatingip_associate_v2.confluence-app (chef): [2018-07-18T11:49:33-05:00] FATAL: Failed to extract file jdk-8u172-linux-x64.tar.gz!
openstack_compute_floatingip_associate_v2.confluence-app (chef):     
openstack_compute_floatingip_associate_v2.confluence-app (chef):     ================================================================================
openstack_compute_floatingip_associate_v2.confluence-app (chef):     Error executing action `install` on resource 'java_oracle_install[jdk]'
openstack_compute_floatingip_associate_v2.confluence-app (chef):     ================================================================================

openstack_compute_floatingip_associate_v2.confluence-app (chef):     SystemExit
openstack_compute_floatingip_associate_v2.confluence-app (chef):     ----------
openstack_compute_floatingip_associate_v2.confluence-app (chef):     exit

openstack_compute_floatingip_associate_v2.confluence-app (chef):     Cookbook Trace:
openstack_compute_floatingip_associate_v2.confluence-app (chef):     ---------------
openstack_compute_floatingip_associate_v2.confluence-app (chef):     /var/chef/cache/cookbooks/java/resources/oracle_install.rb:114:in `block (2 levels) in class_from_file'
openstack_compute_floatingip_associate_v2.confluence-app (chef):     /var/chef/cache/cookbooks/java/resources/oracle_install.rb:86:in `block in class_from_file'

openstack_compute_floatingip_associate_v2.confluence-app (chef):     Resource Declaration:
openstack_compute_floatingip_associate_v2.confluence-app (chef):     ---------------------
openstack_compute_floatingip_associate_v2.confluence-app (chef):     # In /var/chef/cache/cookbooks/java/recipes/oracle.rb
openstack_compute_floatingip_associate_v2.confluence-app (chef): 
openstack_compute_floatingip_associate_v2.confluence-app (chef):      40: java_oracle_install 'jdk' do
openstack_compute_floatingip_associate_v2.confluence-app (chef):      41:   url tarball_url
openstack_compute_floatingip_associate_v2.confluence-app (chef):      42:   default node['java']['set_default']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      43:   checksum tarball_checksum
openstack_compute_floatingip_associate_v2.confluence-app (chef):      44:   app_home java_home
openstack_compute_floatingip_associate_v2.confluence-app (chef):      45:   bin_cmds bin_cmds
openstack_compute_floatingip_associate_v2.confluence-app (chef):      46:   alternatives_priority node['java']['alternatives_priority']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      47:   retries node['java']['ark_retries']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      48:   retry_delay node['java']['ark_retry_delay']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      49:   connect_timeout node['java']['ark_timeout']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      50:   use_alt_suffix node['java']['use_alt_suffix']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      51:   reset_alternatives node['java']['reset_alternatives']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      52:   download_timeout node['java']['ark_download_timeout']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      53:   proxy node['java']['ark_proxy']
openstack_compute_floatingip_associate_v2.confluence-app (chef):      54:   action :install
openstack_compute_floatingip_associate_v2.confluence-app (chef):      55:   notifies :write, 'log[jdk-version-changed]', :immediately
openstack_compute_floatingip_associate_v2.confluence-app (chef):      56: end
openstack_compute_floatingip_associate_v2.confluence-app (chef):      57:
openstack_compute_floatingip_associate_v2.confluence-app (chef):      58: if node['java']['set_default'] && platform_family?('debian')
openstack_compute_floatingip_associate_v2.confluence-app (chef):      59:   include_recipe 'java::default_java_symlink'
openstack_compute_floatingip_associate_v2.confluence-app (chef):      60: end
openstack_compute_floatingip_associate_v2.confluence-app (chef):      61:
openstack_compute_floatingip_associate_v2.confluence-app (chef): 
openstack_compute_floatingip_associate_v2.confluence-app (chef):     Compiled Resource:
openstack_compute_floatingip_associate_v2.confluence-app (chef):     ------------------
openstack_compute_floatingip_associate_v2.confluence-app (chef):     # Declared in /var/chef/cache/cookbooks/java/recipes/oracle.rb:40:in `from_file'
openstack_compute_floatingip_associate_v2.confluence-app (chef): 
openstack_compute_floatingip_associate_v2.confluence-app (chef):     java_oracle_install("jdk") do
openstack_compute_floatingip_associate_v2.confluence-app (chef):       action [:install]
openstack_compute_floatingip_associate_v2.confluence-app (chef):       updated true
openstack_compute_floatingip_associate_v2.confluence-app (chef):       updated_by_last_action true
openstack_compute_floatingip_associate_v2.confluence-app (chef):       retries 0
openstack_compute_floatingip_associate_v2.confluence-app (chef):       retry_delay 2
openstack_compute_floatingip_associate_v2.confluence-app (chef):       default_guard_interpreter :default
openstack_compute_floatingip_associate_v2.confluence-app (chef):       declared_type :java_oracle_install
openstack_compute_floatingip_associate_v2.confluence-app (chef):       cookbook_name "java"
openstack_compute_floatingip_associate_v2.confluence-app (chef):       recipe_name "oracle"
openstack_compute_floatingip_associate_v2.confluence-app (chef):       url "http://download.oracle.com/otn-pub/java/jdk/8u172-b11/a58eab1ec242421181065cdc37240b08/jdk-8u172-linux-x64.tar.gz"`

**Comment by kraigstrong** [comment]
I am having the same issue. I attempted to 👍 but it doesn't seem to allow me to do so

**Comment by majormoses** [comment]
This is very odd but I was able to go to: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html and after accepting the license I was able to download http://download.oracle.com/otn-pub/java/jdk/8u181-b13/96a7b8442fe848ef90c96a2fad6ed6d1/jdk-8u181-linux-x64.tar.gz I was not able to download the version `8u172`. I feel like something changed in how you can accept the license agreement and if you do not you get a `304` redirect asking you to accept the terms.

**Comment by majormoses** [comment]
I guess they actually removed the version that we are defaulting to, I have proposed #476 which works in my test in vagrant.

**Comment by jsibo** [comment]
Nice @majormoses - I was also able to workaround this by updating our JIRA nodes to java v181 with the checksum & uri
