### ISSUE TITLE
is there any options to install 2 versions of Java on windows with one chef run?

### ISSUE THREAD

**Issue by yamamoto52** [sous-chefs/java#483]
I need to install both versions : 64 and 32 bits 

I tried sth like this in recipe after installation first Java version : 

    node.override['java']['windows']['reboot']          = node['java']['2']['windows']['reboot']
    node.override['java']['windows']['url']             = node['java']['2']['windows']['url']
    node.override['java']['windows']['checksum']        = node['java']['2']['windows']['checksum']
    node.override['java']['windows']['package_name']    = node['java']['2']['windows']['package_name']
    node.override['java']['windows']['public_jre_home'] = node['java']['2']['windows']['public_jre_home']
    node.override['java']['java_home']                  = node['java']['2']['java_home']
    node.override['java']['jdk_version']                = node['java']['2']['jdk_version']

    include_recipe 'java::windows'

but it skips java::windows because it ran before, but with others attributes

**Comment by majormoses** [comment]
I dont think thats currently possible in the cookbook as recipes are run only once and the installer is not a custom resource.

**Comment by majormoses** [comment]
Take a look at what the recipe is doing and then create some logic around looping through some array or hash of java versions to install.
