### ISSUE TITLE
Discussion and investigation: Add AdoptOpenJDK as a install flavor

### ISSUE THREAD

**Issue by majormoses** [sous-chefs/java#501]
This is to grab information relating to #497 and discuss any implications of this

**Comment by majormoses** [comment]
Some reading links:
- https://openjdk.java.net/
- https://adoptopenjdk.net/
- https://docs.google.com/document/d/1nFGazvrCvHMZJgFstlbzoHjpAVwv5DEdnaBr_5pKuHo/edit

**Comment by majormoses** [comment]
This seems legit based on some quick investigation.

**Comment by gabe-brussa** [comment]
I just want to +1 this request, it would be really nice to have this feature merged.

**Comment by tony--** [comment]
+1
Is help needed with fixing up #497?

**Comment by rhollencamp** [comment]
are there plans to merge this into the 3.1 branch as well? a blind cherry pick of the merge commit in to the `release/v3.1.0` branch works for me

**Comment by majormoses** [comment]
I think it really depends on how quickly we can validate and fix everything in master that is unreleased and if we can cut a 4.x release I don't think we will unless there is a very good reason. I did hotfix into the 3.x release path a patch but I dont think we should hotfix for feature releases. @tas50 let me know if you feel otherwise.
