### ISSUE TITLE
Support for Amazon Corretto [Feature Request]

### ISSUE THREAD

**Issue by danjellesma** [sous-chefs/java#507]
Requesting support for Amazon's new Corretto distribution of OpenJDK

https://aws.amazon.com/blogs/opensource/amazon-corretto-no-cost-distribution-openjdk-long-term-support
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/what-is-corretto-8.html
https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by damacus** [comment]
Sounds great! 

Is there anyway we can help you make this PR?

**Comment by duncaan** [comment]
@damacus I opened the above PR for this issue which could use a review: https://github.com/sous-chefs/java/pull/545

**Comment by duncaan** [comment]
released in 4.1.0
