### ISSUE TITLE
systemd_unit resource problems

### ISSUE THREAD

**Issue by dalita** [sous-chefs/java#513]
### Chef-client version
Chef: 14.6.47

### Platform Details
CentOS 7.5
Chef: 14.6.47

### Scenario:
Creating systemd unit using the systemd_unit resource.

### Steps to Reproduce:
systemd_unit 'weblogic.service'

### Actual Result:
 ================================================================================
             Error executing action `create` on resource 'file[/etc/systemd/system/weblogic.service]'
             ================================================================================

             Chef::Exceptions::ValidationFailed
             ----------------------------------
             Proposed content for /etc/systemd/system/weblogic.service failed verification :systemd_unit (Chef::Resource::File::Verification::SystemdUnit)

             Compiled Resource:
             ------------------
             # Declared in

             file("/etc/systemd/system/weblogic.service") do
        action [:create]
        default_guard_interpreter :default
        owner "root"
        group "root"
        mode "0644"
        content "[Unit]\nDescription = WebLogic Adminserver service\n\n[Service]\nType = simple\nExecStart = /home/wluser/domains/DefaultDomain/startWebLogic.sh\nExecStop = /home/wluser/domains/DefaultDomain/bin/stopWebLogic.sh\nUser = wluser\n\n[Install]\nWantedBy = multi-user.target\n"
        verifications [#<Chef::Resource::File::Verification:0x00000000053d2278 @command_opts={}, @command=:systemd_unit, @block=nil, @parent_resource=<file[/etc/systemd/system/weblogic.service] @name: "/etc/systemd/system/weblogic.service" @before: nil @params: {} @provider: nil @allowed_actions: [:nothing, :create, :delete, :touch, :create_if_missing] @action: [:create] @updated: false @updated_by_last_action: false @source_line: nil @guard_interpreter: nil @default_guard_interpreter: :default @elapsed_time: 0 @owner: "root" @group: "root" @mode: "0644" @content: "[Unit]\nDescription = WebLogic Adminserver service\n\n[Service]\nType = simple\nExecStart = /home/wluser/domains/DefaultDomain/startWebLogic.sh\nExecStop = /home/wluser/domains/DefaultDomain/bin/stopWebLogic.sh\nUser = wluser\n\n[Install]\nWantedBy = multi-user.target\n" @verifications: [...] @path: "/etc/systemd/system/weblogic.service">>]
        path "/etc/systemd/system/weblogic.service"
             end

             System Info:
             ------------
             chef_version=14.7.17
             platform=centos
             platform_version=7.5.1804
             ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
             program_name=/opt/chef/bin/chef-client
             executable=/opt/chef/bin/chef-client

           ================================================================================
           Error executing action `create` on resource 'systemd_unit[weblogic.service]'
           ================================================================================

           Chef::Exceptions::ValidationFailed
           ----------------------------------
           file[/etc/systemd/system/weblogic.service] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/system/weblogic.service failed verification :systemd_unit (Chef::Resource::File::Verification::SystemdUnit)

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/oracle_fmw/recipes/install_wls.rb

            66: systemd_unit 'weblogic.service' do
            67:   content(Unit: {
            68:             Description: 'WebLogic Adminserver service'
            69:           },
            70:           Service: {
            71:             Type: 'simple',
            72:             ExecStart: "#{scripts_path}/startWebLogic.sh",
            73:             ExecStop: "#{scripts_path}/bin/stopWebLogic.sh",
            74:             User: os_user
            75:           },
            76:           Install: {
            77:             WantedBy: 'multi-user.target'
            78:           })
            79:   action %i[create enable start]
            80: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/oracle_fmw/recipes/install_wls.rb:66:in `from_file'

           systemd_unit("weblogic.service") do
             action [:create, :enable, :start]
             default_guard_interpreter :default
             declared_type :systemd_unit
             cookbook_name "oracle_fmw"
             recipe_name "install_wls"
             content {:Unit=>{:Description=>"WebLogic Adminserver service"}, :Service=>{:Type=>"simple", :ExecStart=>"/home/wluser/domains/DefaultDomain/startWebLogic.sh", :ExecStop=>"/home/wluser/domains/DefaultDomain/bin/stopWebLogic.sh", :User=>"wluser"}, :Install=>{:WantedBy=>"multi-user.target"}}
             unit_name "weblogic.service"
           end

           System Info:
           ------------
           chef_version=14.7.17
           platform=centos
           platform_version=7.5.1804
           ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

       Running handlers:
       [2018-12-12T21:37:27+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-12-12T21:37:27+00:00] ERROR: Exception handlers complete
       Chef Client failed. 3 resources updated in 28 minutes 25 seconds
       [2018-12-12T21:37:27+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-12-12T21:37:27+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-12-12T21:37:27+00:00] FATAL: Chef::Exceptions::ValidationFailed: systemd_unit[weblogic.service]had an error: Chef::Exceptions::ValidationFailed: file[/etc/systemd/system/weblogic.service] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/system/weblogic.service failed verification :systemd_unit (Chef::Resource::File::Verification::SystemdUnit)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <default-centos-75>.  Please see .kitchen/logs/default-centos-75.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by josephholsten** [comment]
See esp:
``` 
file[/etc/systemd/system/weblogic.service] (dynamically defined) had an error: Chef::Exceptions::ValidationFailed: Proposed content for /etc/systemd/system/weblogic.service failed verification :systemd_unit (Chef::Resource::File::Verification::SystemdUnit)
```

**Comment by josephholsten** [comment]
@dalita I'm not sure I understand why you're filing this ticket with us. This java cookbook doesn't interact with systemd or weblogic. Is there anything we can help you with?

**Comment by dalita** [comment]
@josephholsten 
Hi, sorry, for so much searching I found the error in this thread and that's why I post it here and I thought you could help me.
