### ISSUE TITLE
[ppc64el] node[java][java_home] is set to /usr/lib/jvm/java-8-openjdk-i386

### ISSUE THREAD

**Issue by docwhat** [sous-chefs/java#522]
### Cookbook version

java 2.2.1

### Chef-client version

chef-client 14

### Platform Details
Ubuntu 18.04 on ppc64le (or ppc64el in debian-speak)

### Scenario:

The cookbook sets `node['java']['java_home']` incorrectly:

- It is being set to `/usr/lib/jvm/java-8-openjdk-i386`
- But I expect `/usr/lib/jvm/java-8-openjdk-ppc64el`

### Steps to Reproduce:

Use the Java cookbook on an ubuntu ppc64le system system.

### Expected Result:

I expect `node['java']['java_home']` to be `/usr/lib/jvm/java-8-openjdk-ppc64el`.

### Actual Result:

The cookbook sets `node['java']['java_home']` to `/usr/lib/jvm/java-8-openjdk-i386`.

**Comment by JohnRoesler** [comment]
I think it's in https://github.com/sous-chefs/java/blob/master/recipes/set_attributes_from_version.rb

**Comment by docwhat** [comment]
I thought it might too, but `i386` isn't in that file. 😃

**Comment by damacus** [comment]
This will shortly need to be set manually via the download URL as we default to x86_64 for the download. As  this is probably the 5% case we're not going to support it in the medium term.
