### ISSUE TITLE
Unable to install Openjdk 10 version

### ISSUE THREAD

**Issue by vijaypatnana** [sous-chefs/java#526]
### Cookbook version
[3.2.0]

### Chef-client version
[12.14.89]

### Platform Details
[CentOS, AWS]

### Scenario:
[Trying to install openjdk 10 version]

### Steps to Reproduce:
I gave the below attributes and mentioned this - include_recipe 'java' in the recipe

default['java']['jdk_version'] = '10'
default['java']['install_flavor'] = 'openjdk'
default['java']['tarball'] = 'https://download.java.net/java/GA/jdk10/10.0.2/19aef61b38124481863b1413dce1855f/13/openjdk-10.0.2_linux-x64_bin.tar.gz'
default['java']['tarball_checksum'] = 'f3b26abc9990a0b8929781310e14a339a7542adfd6596afb842fa0dd7e3848b2'

Did I miss any attributes here? Please let me know. Thanks in Advance!

**Comment by damacus** [comment]
Closing as OpenJDK is now EOL, and OpenJDK 11 is the LTS version. 

We will also be moving to custom resources and fully integration testing the current and LTS versions of OpenJDK. 

Thanks!
