### ISSUE TITLE
Release cookbook with adoptopenjdk recipe

### ISSUE THREAD

**Issue by varshavaradarajan** [sous-chefs/java#536]
### Cookbook version
3.2.1
### Chef-client version

13

### Scenario:

I want to use adoptopenjdk to install java 11. The README on GitHub shows that `adoptopenjdk` can be provided as an `install_flavour`.

**Comment by Nklya** [comment]
As a workaround, you can use this GitHub repo as a source.

**Comment by damacus** [comment]
We're waiting on #589 to get released with it's custom resource (note, it's no longer a recipe) 

Thanks!
