### ISSUE TITLE
Update Changelog for 3.2.1 release

### ISSUE THREAD

**Issue by isuftin** [sous-chefs/java#537]
### Cookbook version
3.2.1

The Changelog has not been changed to reflect the 3.2.1 release. What's new?

**Comment by Nklya** [comment]
Also you haven't bumped version in metadata, but pushed 3.2.1 to supermarket. And it looks like this 3.2.1 is the same as 3.2.0

**Comment by Brantone** [comment]
This had me confused for a while as well ... what's the actual current state??

**Comment by Brantone** [comment]
With `4.0.0` being released, this should be closed as "resolved".

**Comment by damacus** [comment]
Hey, can you both jump onto the sous-chefs channel on the chef slack please?

It's be great to have this surfaced there if it's possible (and recorded here)
