### ISSUE TITLE
allowing the payload to be downloaded into an user defined location

### ISSUE THREAD

**Issue by gaelik** [sous-chefs/java#538]
### Cookbook version
3.2.1

### Chef-client version
14.7.17

### Platform Details
Linux Redhat 7

### Scenario:
We are trying to use the cookbook to install java, but /var/chef does not have enough space to download the payload on our systems and we wanted to know if instead of being hardcoded to Chef::Config[:file_cache_path], the cookbook could allow the user to specify a landing zone for the payload, maybe defaulting to Chef::Config[:file_cache_path] for compatibility purpose if not setup...

### Steps to Reproduce:
We have a dedicated 500 Meg /var/chef filesystem on all our servers and we are forcing logs and cache into it.

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
If we could specify another location, we would expect the install to go thru

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
/var/chef gets full... and the cookbook fails.

**Comment by majormoses** [comment]
I'd be supportive of exposing this as an attribute and defaulting to the cache location. PRs are welcome.

**Comment by teknomar7** [comment]
Any update on when we can expect a solution for this?  Otherwise, I will have to find an alternative method or clone and modify this cookbook.

**Comment by majormoses** [comment]
> or clone and modify this cookbook

I welcome PRs

**Comment by teknomar7** [comment]
PR 554 submitted for this, but fails automated lint tests due to "accept license" prompt from chef exec.

**Comment by majormoses** [comment]
closed via #554 and released in https://supermarket.chef.io/cookbooks/java/versions/4.2.0
