### ISSUE TITLE
No such cookbook: homebrew

### ISSUE THREAD

**Issue by sbutt** [sous-chefs/java#556]
### Cookbook version
4.1.0

### Chef-client version
Chef: 13.7.16

### Platform Details
Red Hat Enterprise Linux Server release 7.6 (Maipo)

### Scenario:
Trying to run cookbook which calls java, but it's insisting it needs homebrew (even though this is not macOs, it's RHEL).

### Steps to Reproduce:
I am using the Kafka and Zookeeper recipes from Bloomberg, which includes Java.

### Expected Result:
Expect cookbook to converge.

### Actual Result:
================================================================================
Error Resolving Cookbooks for Run List:
================================================================================

Missing Cookbooks:
------------------
No such cookbook: homebrew

Expanded Run List:
------------------
* ip::user
* ip::java
* ip::connect-direct
* ip::node
* ip::python
* ip::jenkins-key
* ip::imagemagick
* ip::ghostscript
* ip::kafka
* ip::ip

System Info:
------------
chef_version=13.7.16
platform=redhat
platform_version=7.6
ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]
program_name=chef-client worker: ppid=90194;start=09:16:33;
executable=/opt/chef/bin/chef-client

Entirely possible I'm doing something wrong here, and it's not a Java cookbook issue, but I'm not sure how to tell. The README *says* it requires homebrew

**Comment by damacus** [comment]
Homebrew is needed as part of the core dependencies of this cookbook, like the Windows cokobook used to be. 

Marking as resolved, as you just need to upload homebrew to your Chef server. The code will not get run unless you call the MacOS recipe. 

Thanks,
Sous-Chefs
