### ISSUE TITLE
windows install flavor should allow for AdoptOpenJDK, OpenJDK, etc

### ISSUE THREAD

**Issue by bokaklav** [sous-chefs/java#564]
### :speaking_head: Foreword

For the windows flavor only the Oracle Java appears to be supported.  My organization is removing Oracle Java in favor of AdoptOpenJDK.  The windows flavor does not allow for the AdoptOpenJDK package

## :person_frowning: Problem Statement

Attributes do not appear to allow for a windows server to be installed with alternative java packages such as AdoptOpenJDK.  Even by overriding the package name the AdoptOpenJDK package requires additional parameters.

## :grey_question: Possible Solution

**Option 1:** Remove windows 'flavor' and have flavors refer only to Java packages.  Cookbooks could alternatively detect system os on their own and/or the user could override with a system specific attribute.

**Option 2:** If option 1 is not realistic the existing windows cookbook could allow for alternative arguments to the msi package.  Through overrides on the package this almost works with the AdoptOpenJDK msi package, but it requires additional parameters to make it a silent install.
   
## :heavy_plus_sign: Additional context

- Mac support request #594

**Comment by astryia** [comment]
We've faced with the same problem:

> Mixlib::ShellOut::ShellCommandFailed: windows_package[AdoptOpenJDK JDK with Hotspot 8.0.222.10 (x64)] (java::windows line 99) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1639'
---- Begin output of msiexec /qn /i "c:\chef\cache\openjdk8u-jdk_x64_windows_hotspot_8u222b10.msi"  /s  ----
STDOUT: 
STDERR: 
---- End output of msiexec /qn /i "c:\chef\cache\openjdk8u-jdk_x64_windows_hotspot_8u222b10.msi"  /s  ----
Ran msiexec /qn /i "c:\chef\cache\openjdk8u-jdk_x64_windows_hotspot_8u222b10.msi"  /s  returned 1639

Looks like AdoptOpenJDK msi doesn't support **/s** parameter

**Comment by bokaklav** [comment]
> We've faced with the same problem:
> 
> > Mixlib::ShellOut::ShellCommandFailed: windows_package[AdoptOpenJDK JDK with Hotspot 8.0.222.10 (x64)] (java::windows line 99) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1639'
> > ---- Begin output of msiexec /qn /i "c:\chef\cache\openjdk8u-jdk_x64_windows_hotspot_8u222b10.msi"  /s  ----
> > STDOUT:
> > STDERR:
> > ---- End output of msiexec /qn /i "c:\chef\cache\openjdk8u-jdk_x64_windows_hotspot_8u222b10.msi"  /s  ----
> > Ran msiexec /qn /i "c:\chef\cache\openjdk8u-jdk_x64_windows_hotspot_8u222b10.msi"  /s  returned 1639
> 
> Looks like AdoptOpenJDK msi doesn't support **/s** parameter

My team got around this by overriding the resource in windows.rb

`java_home_win = win_friendly_path(node['java']['java_home'])

# Java cookbook doesn't provide proper paramaters for AdoptOpenJDK msi installer like it does for the tarball on linux.
# We're overriding this resource.
additional_options = "ADDLOCAL=FeatureMain,FeatureEnvironment,FeatureJarFileRunWith,FeatureJavaHome INSTALLDIR=\"#{java_home_win}\" /quiet"

r = resources(windows_package: node['java']['windows']['package_name'])
r.options additional_options`

**Comment by wbp2019** [comment]
I'm facing the same issue... could you tell me how did you implement it? I mean should I download java coobook and modify windows.rb recipe localy or can I add some attributes or create new recipe on my cookbook and still use java coobook from supermarket? Thanks

**Comment by astryia** [comment]
I've implemented wrapper cookbook, which call original cookbook for all cases except adoptopenjdk installation on Windows. And I've created my own recipe which installs adoptopenjdk  from msi with valid arguments.
Drawback of this approach is that you need to use wrapper cookbook everywhere instead of original java cookbook.

**Comment by wbp2019** [comment]
Ok, thanks for tips. So now we have to wait for new release. Hopefully it will be soon ;)

**Comment by damacus** [comment]
Right now we're working on moving the non-Oracle JDKs on Linux platforms to custom resources. So this will happen post rework.

#589 is the start of fixing this bug, but we have yet to add windows testing and URLs to this cookbook. If you want to add a PR to add the URLs after #589 has been merged, without testing that should work.

**Comment by damacus** [comment]
This is now in the pipeline, as we've shipped the new resources for the above resoruces.
