### ISSUE TITLE
OpenJDK install with OS package manager (YUM)

### ISSUE THREAD

**Issue by djessich** [sous-chefs/java#601]
### :speaking_head: Foreword

Support for package based install in OpenJDK resource. This feature has been removed in Cookbook version v8.0.0 and was available until v7.0.0. This breaking change that breaks already managed environments, where installation was performed using package manager.

## :person_frowning: Problem Statement

OpenJDK cannot be installed using YUM on CentOS. Other package manager support on other platforms may also be added.

## :grey_question: Possible Solution

Implement support for installation using package manager in `openjdk_install` resource.

## :arrow_heading_up: Describe alternatives you've considered

Stick to cookbook 7.0.0, as there is no way of doing an OpenJDK install in 8.0.0+.

**Comment by JohnRoesler** [comment]
https://github.com/sous-chefs/java/pull/602
