### ISSUE TITLE
Custom resource name conflict

### ISSUE THREAD

**Issue by shauryagarg2006** [sous-chefs/java#616]
Cookbook Version : 8.1.2

The name of the resource 
https://github.com/sous-chefs/java/blob/master/resources/openjdk_install.rb#L1
and here
https://github.com/sous-chefs/java/blob/master/resources/openjdk_source_install.rb#L1

is same/conflicting. Is that intentional or by mistake? 

I am getting error when using:
```
openjdk_install '8' do
  install_type 'package'
end
```
```
FATAL: NoMethodError: undefined method `install_type' for Custom resource java_openjdk_source_install from cookbook java
```

Because it is picking up the wrong custom resource.

**Comment by damacus** [comment]
I'm closing this as it doesn't use the standard template and is missing key details like chef-client version which we need to debug issues. 

Please reopen with the correct template.
