### ISSUE TITLE
Please remove references to supporting Oracle/IBM

### ISSUE THREAD

**Issue by Lasering** [sous-chefs/java#622]
It is really misleading to say:

> This cookbook installs a Java JDK/JRE. It defaults to installing OpenJDK, but it can also install Oracle, IBM JDKs or AdoptOpenJDK.

When in fact Oracle and IBM have been dropped in version 8.0.0 of the cookbook.

**Comment by damacus** [comment]
If someone would like to submit a PR we'll be really happy to receive these corrections.
