### ISSUE TITLE
Corretto `version` property should accept specific versions, not just latest major versions

### ISSUE THREAD

**Issue by jakauppila** [sous-chefs/java#628]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

Currently, the `version` property on the `corretto_install` resource accepts a major version which then builds the latest major version url with `default_corretto_url`, which means I could not specify `11.0.7.10.1` without providing the full url and checksum value myself.

## :grey_question: Possible Solution

Add the ability to specify specific versions and build the appropriate URL to download the correct package. We could maintain the current ability by detecting only a major version and downloading the latest version.

Along with #607, we should also dynamically pull back the MD5 checksum as well. 

## :heavy_plus_sign: Additional context

URL download format is documented here: https://docs.aws.amazon.com/corretto/latest/corretto-11-ug/downloads-list.html

Though it appears to only be clearly documented for the `latest` version. I have submitted feedback for AWS to provide additional documentation for downloading specific versions rather than just guessing; I will also follow-up with AWS with support.

**Comment by damacus** [comment]
I think this is actually working as I designed. Limiting Corretto down to a current/previous minor version will probably lead to code sprawl.

**Comment by jakauppila** [comment]
So this is what I want to do, install a specific version and not just grab the latest 11 release.

```ruby
corretto_install 'install 11.0.4.11.1' do
  version '11.0.4.11.1'
end
```

My thought is this:

- `default_corretto_url` will continue to take in the version specified on the resource
- if 'version' is `8` or `11`, return the current `latest` url it does today
- Otherwise construct the specific version URL (utilizing ohai attributes for architecture, etc) to pull the appropriate version down
  - Example: 
    - https://corretto.aws/downloads/resources/11.0.7.10.1/amazon-corretto-11.0.7.10.1-linux-x64.tar.gz

I figured this sort of behavior is probably beneficial for all rather than keeping the URL-building in our wrapper cookbook.

I'm happy to work on this, just wanted to make sure we were on the same page first.

**Comment by damacus** [comment]
Oh this makes loads of sense! I like it. 

having it match only 8 or 11 then falling back to helping you construct the URL makes sense.

**Comment by jakauppila** [comment]
I have opened an issue over on corretto/corretto11 asking about documentation around the specific version url structure, just to have more clarity: https://github.com/corretto/corretto-11/issues/112

**Comment by jakauppila** [comment]
I'll work on this functionality and may submit a WIP PR, but may not want it merged until AWS publishes/documents a structured version URL for specific Corretto versions.

I've heard from our AWS TAM that the Corretto team will be doing this, but won't commit to a timeframe yet.

**Comment by jakauppila** [comment]
Here's some rambling thoughts about this issue.

Today, the resource takes both `version` and `full_version`.

`version` is used for the following:
 - Retrieve the 'latest' friendly URL via [default_corretto_url](https://github.com/sous-chefs/java/blob/master/libraries/corretto_helpers.rb#L8)
 - Retrieve the 'latest' checksum via [default_corretto_checksum](https://github.com/sous-chefs/java/blob/master/libraries/corretto_helpers.rb#L16) (hardcoded in the cookbook, so gets out of date quickly)
 - Help define the default `java_home` along with `full_version` if defined, otherwise is defaulted to a hardcoded `full_version` (which has the same problem as above)

`full_version` is used for the sole purpose of defining the full path of the default `java_home` directory structure.

So I'm thinking:
 - Condense down to only a single `version` property where we can evaluate to see if it's simply a major version (8, 11, or 15) or a specific version
   - If major version, use the friendly 'latest' URLs. Dynamically retrieve the checksum via friendly URL
   - If specific version, use the undocumented 'version' URLs. There is currently no method for retrieving the checksum as they are not actively published right now.
   - The friendly URLs are simply a 302 redirect to the latest version; **is there any precedence in other cookbooks for parsing the resulting downloaded filename for the full version to use elsewhere in the resource?** This naturally breaks down if someone supplies their own download URL that doesn't follow the same naming scheme.

One caveat on the `checksum` is that currently the resource passes it directly to `remote_file` which appears to expect SHA256, whereas the AWS published the MD5 on the "friendly" urls.

Or:
  - Stop allowing the "friendly" latest 8, 11 versions and force specifying a specific version, where checksum must be manually supplied until AWS publishes them via repeatable means.

We also deploy java on application servers and configure those apps to use an explicit version, so I'd probably look to add a property to skip the alternatives configuration.

**Comment by jakauppila** [comment]
There's another issue out on corretto/corretto-jdk about exposing an API for fetching versions, I think this is the ideal state for being able to bring in this functionality into the cookbook. https://github.com/corretto/corretto-jdk/issues/14
