### ISSUE TITLE
Feature: STARTTLS parameter for the java_certificate resource

### ISSUE THREAD

**Issue by freakinhippie** [sous-chefs/java#634]
## :person_frowning: Problem Statement

The `java_certificate` resource is currently unable to fetch a TLS certificate from endpoints that use a TLS negotiation protocol other than HTTPS. The ability to fetch certificates from other endpoints such as _smtp_, _mysql_, _ldap_, etc would be very useful.

## :grey_question: Possible Solution

Add a `starttls` property to the `java_certificate` resource and pass it to the openssl command as needed.

## :arrow_heading_up: Describe alternatives you've considered

Short of using an entirely different resource or shelling out directly, this feature is missing.

## :heavy_plus_sign: Additional context

I'm working on a pull request for this.

**Comment by EMH333** [comment]
Present in release 8.4.0
