### ISSUE TITLE
Bad resource naming for openjdk_source_install

### ISSUE THREAD

**Issue by jimbodragon** [sous-chefs/java#645]
## :ghost: Brief Description

Try to use the resource openjdk_install but this resource us already use by openjdk_source_install.rb

## :pancakes: Cookbook version
8.4.0

## :woman_cook:  Chef-Infra Version
15.0.300

## :tophat: Platform details
Ubuntu 18.04 LTS

## Steps To Reproduce

1. Create a cookbook/recipe using:

```ruby
openjdk_install "core" do
  version "14"
  default true
  install_type "package"
end
```

2. Compile the cookbook
3. Error is:

```
NoMethodError
    -------------
    undefined method `install_type' for Custom resource java_openjdk_source_install from cookbook java
```

## :police_car: Expected behavior
Able to use openjdk_install as main wrapper for openjdk_pkg_install and openjdk_source_install

**Comment by ramereth** [comment]
@jimbodragon can you please verify that #646 fixes your issue?
