### ISSUE TITLE
OpenJDK variant typo

### ISSUE THREAD

**Issue by yacn** [sous-chefs/java#701]
### :speaking_head: Foreword

Thank for taking the time to fill this bug report fully. Without it we may not be able to fix the bug, and the issue may be closed without resolution.

## :ghost: Brief Description

`openjdk` install has a typo in the variants (open***d***jdk when it should be `openjdk`)

## :pancakes: Cookbook version

12.0.0

## :woman_cook:  Chef-Infra Version

doesn't matter

## :tophat: Platform details

doesn't mattrer

## Steps To Reproduce

try converging the cookbook to install openjdk by default

## :police_car: Expected behavior

It shouldn't fail

## :heavy_plus_sign: Additional context

typo came from this pr: https://github.com/sous-chefs/java/pull/676

you can see this failing in the tests, for example: https://github.com/sous-chefs/java/actions/runs/6353246294/job/17257649376

**Comment by damacus** [comment]
Thanks. That's not surprising that a typo came in! Thanks for noting this I'll get this fixed now

**Comment by damacus** [comment]
Fixed via #702
